# Generated by Django 6.0.6 on 2026-06-24 06:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Yoruba/Southwest", "Yoruba / Southwest"),
                            ("Southeast/Igbo", "Southeast / Igbo"),
                            ("Hausa/North", "Hausa / North"),
                            ("South-South", "South-South"),
                        ],
                        default="General",
                        max_length=50,
                    ),
                ),
                (
                    "meal_time",
                    models.CharField(
                        help_text="Comma-separated: breakfast,lunch,dinner,snack",
                        max_length=100,
                    ),
                ),
                ("calories_kcal", models.PositiveIntegerField()),
                ("protein_g", models.FloatField()),
                ("carb_g", models.FloatField()),
                ("fat_g", models.FloatField()),
                (
                    "goal_suitability",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("maintenance", "Maintenance"),
                            ("all", "All Goals"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced"),
                            ("high-protein", "High Protein"),
                            ("low-calorie", "Low Calorie"),
                            ("energy-rich", "Energy Rich"),
                            ("vegetarian", "Vegetarian"),
                            ("indulgent", "Indulgent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("taste_profile", models.CharField(max_length=100)),
                (
                    "prep_time",
                    models.CharField(
                        choices=[
                            ("short", "Short (< 20 mins)"),
                            ("medium", "Medium (20-45 mins)"),
                            ("long", "Long (> 45 mins)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("low", "Low (₦0 - ₦1,000)"),
                            ("medium", "Medium (₦1,000 - ₦3,000)"),
                            ("high", "High (₦3,000+)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
                "ordering": ["food_name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ]
                    ),
                ),
                (
                    "height_cm",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(250),
                        ]
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary (little or no exercise)"),
                            ("light", "Light (1-3 days/week)"),
                            ("moderate", "Moderate (3-5 days/week)"),
                            ("active", "Active (6-7 days/week)"),
                            ("very_active", "Very Active (hard exercise daily)"),
                        ],
                        default="sedentary",
                        max_length=20,
                    ),
                ),
                (
                    "health_goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Lose Weight"),
                            ("muscle_gain", "Gain Muscle"),
                            ("maintenance", "Maintain Weight"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "regional_preference",
                    models.CharField(
                        choices=[
                            ("general", "General (No Preference)"),
                            ("yoruba_southwest", "Yoruba / Southwest"),
                            ("igbo_southeast", "Igbo / Southeast"),
                            ("hausa_north", "Hausa / North"),
                            ("south_south", "South-South"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("is_diabetic", models.BooleanField(default=False)),
                ("is_hypertensive", models.BooleanField(default=False)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("bmi", models.FloatField(blank=True, null=True)),
                ("bmr", models.FloatField(blank=True, null=True)),
                ("tdee", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Profile",
                "verbose_name_plural": "Health Profiles",
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(default="My Meal Plan", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Plan",
                "verbose_name_plural": "Meal Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "portion_size",
                    models.FloatField(default=1.0, help_text="1.0 = standard serving"),
                ),
                ("actual_calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.meal",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="recommender.mealplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Plan Entry",
                "verbose_name_plural": "Meal Plan Entries",
                "ordering": ["day", "meal_time"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_model_used",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("lightgbm", "LightGBM"),
                            ("ann", "ANN (Neural Network)"),
                            ("lstm", "LSTM"),
                            ("ensemble", "Ensemble"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Recommendation confidence score (0.0 - 1.0)"
                    ),
                ),
                (
                    "ensemble_score",
                    models.FloatField(
                        blank=True,
                        help_text="Combined score from all models",
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(help_text="1 = top recommendation"),
                ),
                (
                    "was_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Did the user act on this recommendation?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "ordering": ["-created_at", "rank"],
            },
        ),
        migrations.CreateModel(
            name="MealFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 - Didn't like it"),
                            (2, "2 - It was okay"),
                            (3, "3 - Good"),
                            (4, "4 - Really good"),
                            (5, "5 - Loved it"),
                        ]
                    ),
                ),
                (
                    "was_cooked",
                    models.BooleanField(
                        default=False, help_text="Did the user cook this at home?"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="recommender.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Feedback",
                "verbose_name_plural": "Meal Feedbacks",
                "ordering": ["-created_at"],
                "unique_together": {("user", "meal")},
            },
        ),
    ]
