# Generated by Django 6.0.6 on 2026-07-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplanentry",
            name="match_score",
            field=models.FloatField(
                default=0.5,
                help_text="LightGBM prediction score at time of planning, 0-1",
            ),
        ),
    ]
