# Generated by Django 6.0.6 on 2026-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_mealplanentry_match_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthprofile",
            name="health_goal",
            field=models.CharField(
                choices=[
                    ("weight_loss", "Lose Weight"),
                    ("weight_gain", "Gain Weight"),
                    ("maintenance", "Maintain Weight"),
                ],
                default="maintenance",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="goal_suitability",
            field=models.CharField(
                choices=[
                    ("weight_loss", "Weight Loss"),
                    ("weight_gain", "Weight Gain"),
                    ("maintenance", "Maintenance"),
                    ("all", "All Goals"),
                ],
                max_length=20,
            ),
        ),
    ]
