# Generated by Django 6.0.6 on 2026-07-22 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0005_meal_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Add New Meal"),
                            ("update", "Edit Existing Meal"),
                            ("delete", "Delete Meal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Proposed field values, e.g. {'food_name': 'Jollof Rice', 'calories_kcal': 620, ...}",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_meal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The meal being edited/deleted. Blank for new meal proposals.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_edits",
                        to="recommender.meal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Edit Proposal",
                "verbose_name_plural": "Meal Edit Proposals",
                "ordering": ["-created_at"],
            },
        ),
    ]
