# Generated by Django 6.0.6 on 2026-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_mealedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealedit',
            name='image',
            field=models.ImageField(blank=True, help_text='Proposed image, applied to the meal on approval.', null=True, upload_to='meal_edit_uploads/'),
        ),
    ]
