# Generated by Django 6.0.6 on 2026-07-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_mealedit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
